version: '3.8'

services:
  backend:
    build: ./backend
    container_name: student-backend
    ports:
      - "5000:5000"
    networks:
      - student-net

  frontend:
    build: ./frontend
    container_name: student-frontend
    ports:
      - "80:80"
    networks:
      - student-net

networks:
  student-net:
    driver: bridge

